"""
Django settings for faqbot project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv is optional; on Render you'll set real env vars instead

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-&-z3^j7b9=v)-d$_cwu5d5q6$23-gd=x^whus6*i-uqs=6+mt^',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    "jazz-chatbot.vercel.app",
    "localhost",
    "127.0.0.1",
    "jazzchatbotv21-38z45lp9l-rehan-aa59.vercel.app"
]
# --- WhatsApp Cloud API settings (from Meta App Dashboard) ---
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')
# Any string you choose yourself - you'll enter the same value into the
# Meta App Dashboard webhook setup screen.
WHATSAPP_VERIFY_TOKEN = os.environ.get('WHATSAPP_VERIFY_TOKEN', 'change-me')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'faqbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'faqbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

import shutil
import logging

_db_logger = logging.getLogger('faqbot.db_setup')

# On a read-only deployment filesystem (e.g. Vercel), SQLite needs a
# writable file. PROBING for actual writability (rather than trusting a
# platform-specific env var name) is more portable, but has a subtlety:
# a directory can allow creating NEW files while a specific EXISTING file
# in it (like our committed db.sqlite3) still carries its own read-only
# permission bits from how the platform packaged it. So we check the
# actual candidate file's writability directly, not just the directory's.
#
# Also fixed: shutil.copy() preserves the SOURCE file's permission bits,
# so copying a read-only-bundled db.sqlite3 into /tmp produced a copy
# that was STILL read-only despite /tmp itself being writable - fixed by
# explicitly chmod'ing the copy afterward.
def _resolve_writable_db_path():
    candidate = BASE_DIR / 'db.sqlite3'

    if candidate.exists():
        try:
            with open(candidate, 'r+b'):
                pass
            _db_logger.warning('DB SETUP: using existing writable file at %s', candidate)
            return candidate
        except OSError as exc:
            _db_logger.warning('DB SETUP: %s exists but open(r+b) failed (%s) - falling back to /tmp', candidate, exc)
    else:
        try:
            probe = BASE_DIR / '.write_test'
            probe.touch()
            probe.unlink()
            _db_logger.warning('DB SETUP: no existing db.sqlite3, but %s is writable - will create it there', BASE_DIR)
            return candidate
        except OSError as exc:
            _db_logger.warning('DB SETUP: %s is not writable (%s) - falling back to /tmp', BASE_DIR, exc)

    # Fall back to /tmp (writable scratch space on Vercel and similar platforms).
    runtime_db = Path('/tmp/db.sqlite3')
    if not runtime_db.exists():
        if candidate.exists():
            shutil.copy(candidate, runtime_db)
            _db_logger.warning('DB SETUP: copied %s -> %s', candidate, runtime_db)
        else:
            runtime_db.touch()
            _db_logger.warning('DB SETUP: created empty new db at %s', runtime_db)
    os.chmod(runtime_db, 0o666)  # force-writable regardless of source permissions
    _db_logger.warning('DB SETUP: final path in use: %s (writable=%s)', runtime_db, os.access(runtime_db, os.W_OK))
    return runtime_db


_db_path = _resolve_writable_db_path()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
